"""claude-commit -- automated git commit with rule enforcement.

Auto-stages files, validates messages, enforces no-attribution rules,
and runs pre-commit with auto-fix.

Usage:
    uv run claude-commit -m "feat: add bus tool"
    uv run claude-commit --auto                    # Auto-generate message
    uv run claude-commit --dry-run                 # Preview only
    uv run claude-commit file1.py file2.py -m "..."
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

# Forbidden attribution patterns (from rules/00-no-attribution.md)
ATTRIBUTION_PATTERNS = [
    r"(?i)co-authored-by",
    r"(?i)generated by",
    r"(?i)assisted by",
    r"(?i)created with",
    r"(?i)\b(AI|LLM|model|assistant|Claude|ChatGPT|Copilot|Gemini)\b",
    r"(?i)# AI-generated",
    r"(?i)# auto-formatted",
    r"(?i)# produced by",
]

# Secret file patterns to block
SECRET_PATTERNS = [
    r"\.env$",
    r"\.env\..*$",
    r"\.pem$",
    r"\.key$",
    r"\.crt$",
    r"\.secret$",
    r"credentials\.",
    r"secrets/",
    r"\.ssh/",
]

# Conventional commit types
COMMIT_TYPES = [
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "test",
    "chore",
    "ci",
    "build",
    "perf",
]


def main() -> int:
    parser = argparse.ArgumentParser(description="Automated git commit with rule enforcement")
    parser.add_argument("files", nargs="*", help="Files to commit (default: all staged)")
    parser.add_argument("-m", "--message", help="Commit message")
    parser.add_argument("--auto", action="store_true", help="Auto-generate message from diff")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be committed")
    parser.add_argument("--force", action="store_true", help="Force commit despite warnings")
    parser.add_argument("--no-verify", action="store_true", help="Skip pre-commit (not recommended)")
    args = parser.parse_args()

    # Check for secrets in staged files
    staged_files = _get_staged_files()
    if not staged_files:
        print("No staged changes to commit.")
        return 1

    secrets_found = _check_secrets(staged_files)
    if secrets_found and not args.force:
        print("ERROR: Potential secrets detected in staged files:")
        for f in secrets_found:
            print(f"  - {f}")
        print("\nRemove secrets or use --force to override (not recommended).")
        return 1

    # Stage specific files if provided
    if args.files:
        _stage_files(args.files)

    # Get or generate commit message
    message = args.message
    if args.auto:
        message = _generate_message()
        if not message:
            print("ERROR: Could not auto-generate commit message. Provide -m instead.")
            return 1

    if not message:
        print("ERROR: Commit message required. Use -m or --auto.")
        return 1

    # Validate and sanitize message
    message = _sanitize_message(message)
    if not _is_conventional_commit(message):
        print(f"WARNING: Message does not follow conventional commit format.")
        print(f"Expected: <type>: <description> where type is one of: {', '.join(COMMIT_TYPES)}")
        if not args.force:
            print("Use --force to commit anyway, or fix the message.")
            return 1

    if args.dry_run:
        print("=== DRY RUN ===")
        print(f"Files to commit: {len(staged_files)}")
        for f in staged_files[:10]:
            print(f"  - {f}")
        if len(staged_files) > 10:
            print(f"  ... and {len(staged_files) - 10} more")
        print(f"\nCommit message:\n  {message}")
        print("\n[DRY RUN] No changes committed.")
        return 0

    # Run pre-commit hooks
    if not args.no_verify:
        if not _run_pre_commit():
            print("Pre-commit hooks failed. Fix errors and try again.")
            return 1

    # Create commit (no attribution footer - violates 00-no-attribution.md)
    result = subprocess.run(
        ["git", "commit", "-m", message],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"Commit failed: {result.stderr}")
        return 1

    # Extract commit hash
    match = re.search(r"\[([^\]]+)\s+([a-f0-9]+)\]", result.stdout)
    if match:
        branch = match.group(1)
        commit_hash = match.group(2)
        print(f"Committed: {commit_hash} ({branch})")
    else:
        print("Committed successfully.")

    print(f"Message: {message}")
    return 0


def _get_staged_files() -> list[str]:
    """Get list of staged files."""
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-only"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return []
    return [f.strip() for f in result.stdout.strip().split("\n") if f.strip()]


def _stage_files(files: list[str]) -> None:
    """Stage specific files."""
    subprocess.run(["git", "add"] + files, check=True)


def _check_secrets(files: list[str]) -> list[str]:
    """Check for potential secrets in file list."""
    found = []
    for f in files:
        for pattern in SECRET_PATTERNS:
            if re.search(pattern, f, re.IGNORECASE):
                found.append(f)
                break
    return found


def _sanitize_message(message: str) -> str:
    """Remove attribution patterns from message."""
    for pattern in ATTRIBUTION_PATTERNS:
        message = re.sub(pattern, "", message, flags=re.IGNORECASE)
    # Clean up extra whitespace
    message = re.sub(r"\s+", " ", message).strip()
    # Remove trailing period from subject line
    if message.endswith("."):
        message = message[:-1]
    return message


def _is_conventional_commit(message: str) -> bool:
    """Check if message follows conventional commit format."""
    pattern = r"^(" + "|".join(COMMIT_TYPES) + r")(\([^)]+\))?: .+"
    return bool(re.match(pattern, message))


def _generate_message() -> str | None:
    """Auto-generate commit message from diff stats."""
    result = subprocess.run(
        ["git", "diff", "--cached", "--stat"],
        capture_output=True,
        text=True,
    )
    if not result.stdout.strip():
        return None

    lines = result.stdout.strip().split("\n")
    changed_files = len(lines) - 1  # Exclude stat summary line

    # Detect scope from file paths
    scopes = set()
    for line in lines[:-1]:
        path = line.split("|")[0].strip()
        if "src/" in path:
            parts = path.split("/")
            if len(parts) > 2:
                scopes.add(parts[1])
        elif "tests/" in path:
            scopes.add("test")

    scope = ",".join(sorted(scopes))[:30] if scopes else None

    # Determine commit type
    if any("test" in line for line in lines):
        commit_type = "test"
    elif any("README" in line or ".md" in line for line in lines):
        commit_type = "docs"
    else:
        commit_type = "feat"  # Default

    # Generate message
    if scope:
        return f"{commit_type}({scope}): add changes to {changed_files} files"
    return f"{commit_type}: add changes to {changed_files} files"


def _run_pre_commit() -> bool:
    """Run pre-commit hooks with auto-fix."""
    # Run ruff format
    subprocess.run(["uv", "run", "ruff", "format", "src/"], capture_output=True)

    # Run ruff check with auto-fix
    result = subprocess.run(
        ["uv", "run", "ruff", "check", "--fix", "src/"],
        capture_output=True,
        text=True,
    )
    if "error" in result.stdout.lower() or result.returncode != 0:
        print(f"ruff check failed: {result.stdout}")
        return False

    # Run mdformat
    subprocess.run(
        ["uvx", "--with", "mdformat-frontmatter", "--with", "mdformat-gfm", "mdformat", "."],
        capture_output=True,
    )

    # Run mypy strict
    result = subprocess.run(
        ["uv", "run", "mypy", "src/claude_cli/", "--strict"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"mypy failed: {result.stdout}")
        return False

    return True


if __name__ == "__main__":
    sys.exit(main())
