name: Publish
on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  pypi-publish:
    uses: BrainXio/cicd/.github/workflows/publish-pypa.yml@v1
    secrets: inherit
